### ISSUE TITLE
windows backslash fix

### ISSUE THREAD

**Issue by cyberstorm256** [Briareos/gulp-systemjs-module-name-injector#2]
could you please create a 1.0.3 release? using npm und version 1.0.2 I don't get the fix. Thanks!

**Comment by Briareos** [comment]
Done. Note that you can use `tsc` for native support since version 1.8:
http://stackoverflow.com/a/33976786/232947
https://github.com/ivogabe/gulp-typescript/issues/243

**Comment by cyberstorm256** [comment]
thank you I'll give it a try with tsc 1.8 support
